# Generated by Django 5.2.3 on 2025-12-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_pics/')),
                ('patient_info', models.TextField(blank=True, null=True)),
                ('patient_medications', models.TextField(blank=True, null=True)),
                ('patient_surgeries', models.TextField(blank=True, null=True)),
                ('patient_social_history', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
